//
//  ExampleChildInteractor.swift
//  VIPCleanPOC
//
//  Created by Mohamed Hisham on 10/11/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects
//

import UIKit

class ExampleChildInteractor: ExampleChildInteractorProtocol
{
    weak var presenter: ExampleChildPresenterProtocol?
    
    func viewLoaded() {
    }
    
}

