//
//  ExampleChildCoordinatorProtocol.swift
//  VIPCleanPOC
//
//  Created by Mohamed Hisham on 10/11/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects
//

import Foundation
import UIKit

enum ExampleChildCoordinatorCallbackType {
    case close
    case back
}

typealias ExampleChildCoordinatorCall = ((ExampleChildCoordinatorCallbackType)->())

protocol ExampleChildCoordinatorUseCaseProtocol {
    
    var navigationController: UINavigationController { set get }
}


protocol ExampleChildCoordinatorProtocol {
    
    init(useCase: ExampleChildCoordinatorUseCaseProtocol)
    func start(callback: @escaping ExampleChildCoordinatorCall)
}
