//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects
//

import Foundation

struct ___VARIABLE_sceneName___Resourses {
    
    struct Text {
    
    }

    struct Color {
    
    }

    struct Font {
    
    }

    struct Image {
    
    }
}
