//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects
//

import Foundation

enum ___VARIABLE_sceneName___ControllerCallbackType {
    case close
    case back
}

typealias ___VARIABLE_sceneName___ControllerCallback = ((___VARIABLE_sceneName___ControllerCallbackType) -> ())

protocol ___VARIABLE_sceneName___ControllerProtocol: AnyObject {
    
    var interactor: ___VARIABLE_sceneName___InteractorProtocol { set get }
    var callback: ___VARIABLE_sceneName___ControllerCallback { set get }
     
    var view: ___VARIABLE_sceneName___ViewProtocol? { set get }
    
    func displayOnView(viewModel: ___VARIABLE_sceneName___ViewModelProtocol)
}
