//
//  ExampleCoordinatorProtocol.swift
//  VIPCleanPOC
//
//  Created by Mohamed Hisham on 10/11/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects
//

import Foundation
import UIKit

enum ExampleCoordinatorCallbackType {
    case close
}

typealias ExampleCoordinatorCall = ((ExampleCoordinatorCallbackType)->())

protocol ExampleCoordinatorUseCaseProtocol {
    
    var window: UIWindow { set get }
}


protocol ExampleCoordinatorProtocol {
    
    init(useCase: ExampleCoordinatorUseCaseProtocol)
    func start(callback: @escaping ExampleCoordinatorCall)
}
