//
//  ExampleChildView.swift
//  VIPCleanPOC
//
//  Created by Mohamed Hisham on 10/11/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects
//

import UIKit

class ExampleChildView: UIViewController, ExampleChildViewProtocol {
     
    var callback: ExampleChildViewCallback?
        
    override func viewDidLoad() {
        super.viewDidLoad()
        setupUI()
        self.navigationController?.navigationBar.isHidden = true
    }
    
    func display(viewModel: ExampleChildViewModelProtocol) {
        
    }
    
    @IBAction func backAction(_ sender: Any) {
        backAction()
    }
}

private extension ExampleChildView {
    func setupUI() {
        
    }
    func backAction(){
        self.callback?(.back)
    }
}
