//
//  ExampleChildTests.swift
//  VIPCleanPOC
//
//  Created by Mohamed Hisham on 13/11/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects
//

import XCTest
@testable import VIPCleanPOC

final class ExampleChildTests: XCTestCase {
    func testExample() throws {
    }
}
//MARK: Seeds
fileprivate struct Seeds {
}

//MARK: Spies
fileprivate class InteractorSpy: ExampleChildInteractorProtocol {
    var presenter:ExampleChildPresenterProtocol?
    init(presenter:ExampleChildPresenterProtocol) {
        self.presenter = presenter
    }
}
fileprivate class ControllerSpy: ExampleChildControllerProtocol {
    var interactor: ExampleChildInteractorProtocol
    var callback: ExampleChildControllerCallback
    var view: ExampleChildViewProtocol?
    func displayOnView(viewModel: ExampleChildViewModelProtocol) {
    }
    init(view:ExampleChildViewProtocol, interactor:ExampleChildInteractorProtocol) {
        self.view = view
        self.callback = { _ in
        }
        self.interactor = interactor
    }
}
fileprivate class PresenterSpy: ExampleChildPresenterProtocol {
    var controller: ExampleChildControllerProtocol?
    func processSuccess(result:ServerResponseUserData){
    }
    init(controller:ExampleChildControllerProtocol) {
        self.controller = controller
    }
}
fileprivate class ViewSpy: ExampleChildViewProtocol {
    var callback:ExampleChildViewCallback?
    func display(viewModel:ExampleChildViewModelProtocol) {
    }
}
