//
//  ExampleView.swift
//  VIPCleanPOC
//
//  Created by Mohamed Hisham on 10/11/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects
//

import UIKit

class ExampleView: UIViewController, ExampleViewProtocol {
    //MARK: Callback action
    // 💡 The callback represents the way in which the state of the view is known to the controller
    var callback: ExampleViewCallback?
    
    
    //MARK: UI outlets
    //💡 UI has to be private so no one outside the view can manpulate it in anyway
    @IBOutlet private weak var mobileNumberTextField: UITextField!
    @IBOutlet private weak var emailLabel: UILabel!
    @IBOutlet private weak var balanceLabel: UILabel!
    @IBOutlet private weak var usernameLabel: UILabel!
    

    //MARK: Life cycle
    override func viewDidLoad() {
        super.viewDidLoad()
        self.setupUI()
    }
    //MARK: Display function
    func display(viewModel: ExampleViewModelProtocol) {
        self.usernameLabel.text = viewModel.username
        self.emailLabel.text = viewModel.email
        self.balanceLabel.text = viewModel.balance
    }
    //MARK: Actions
    @IBAction func submitAction(_ sender: Any) {
        self.sumbitAction()
    }
    
    @IBAction func navigateAction(_ sender: Any) {
        self.navigateAction()
    }
}

private extension ExampleView {
    
    func setupUI() {
        
    }
    func navigateAction(){
        self.callback?(.navigate)
    }
    func sumbitAction(){
        guard let text = mobileNumberTextField.text else {return}
        self.callback?(.sumbit(mobile: text))
    }
}
