//
//  ExampleViewProtocol.swift
//  VIPCleanPOC
//
//  Created by Mohamed Hisham on 10/11/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects
//

import Foundation

//💡 The callback type enum represents all the cases that the view will wanna communicate to the next layer (controller)
enum ExampleViewCallbackType {
    case back
    case sumbit(mobile: String)
    case navigate
}

//💡 The callback is a closure with the callback type as an input to determine the state in which the view wants to notify the controller of
typealias ExampleViewCallback = ((ExampleViewCallbackType) -> ())


//💡 This protocol represents the view model protocol the model used to display the view
protocol ExampleViewModelProtocol {
    var username: String { set get }
    var email: String { set get }
    var balance: String { set get }
}

//MARK: View Protocol
protocol ExampleViewProtocol: AnyObject {
    
    var callback: ExampleViewCallback? { set get }
    func display(viewModel: ExampleViewModelProtocol)
}
