//
//  ExampleChildControllerProtocol.swift
//  VIPCleanPOC
//
//  Created by Mohamed Hisham on 10/11/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects
//

import Foundation

enum ExampleChildControllerCallbackType {
    case close
    case back
}

typealias ExampleChildControllerCallback = ((ExampleChildControllerCallbackType) -> ())

protocol ExampleChildControllerProtocol: AnyObject {
    
    var interactor: ExampleChildInteractorProtocol { set get }
    var callback: ExampleChildControllerCallback { set get }
     
    var view: ExampleChildViewProtocol? { set get }
    
    func displayOnView(viewModel: ExampleChildViewModelProtocol)
}
