//
//  ExampleChildController.swift
//  VIPCleanPOC
//
//  Created by Mohamed Hisham on 10/11/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects
//

import Foundation

class ExampleChildController: ExampleChildControllerProtocol {
    
    var interactor: ExampleChildInteractorProtocol
    var callback: ExampleChildControllerCallback
    
    init(interactor: ExampleChildInteractorProtocol, callback: @escaping ExampleChildControllerCallback) {
        self.interactor = interactor
        self.callback = callback
    }
    
    weak var view: ExampleChildViewProtocol? {
        
        didSet {
            view?.callback = processViewCallback()
        }
    }
    
    func displayOnView(viewModel: ExampleChildViewModelProtocol) {
        view?.display(viewModel: viewModel)
    }
}

private extension ExampleChildController {
    
    func processViewCallback() -> ExampleChildViewCallback {
        
        return {[weak self] type in
            guard let self = self else { return }
            switch type {
            case .back:
                self.callback(.back)
            }
        }
    }
}
