//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects
//

import Foundation
import UIKit

enum ___VARIABLE_sceneName___CoordinatorCallbackType {
    case close
}

typealias ___VARIABLE_sceneName___CoordinatorCall = ((___VARIABLE_sceneName___CoordinatorCallbackType)->())

protocol ___VARIABLE_sceneName___CoordinatorUseCaseProtocol {
    
    var navigationController: UINavigationController { set get }
}


protocol ___VARIABLE_sceneName___CoordinatorProtocol {
    
    init(useCase: ___VARIABLE_sceneName___CoordinatorUseCaseProtocol)
    func start(callback: @escaping ___VARIABLE_sceneName___CoordinatorCall)
}
