//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects
//

import Foundation
import UIKit

class ___VARIABLE_sceneName___Coordinator: ___VARIABLE_sceneName___CoordinatorProtocol, BaseCoordinatorProtocol {
    
    var dependencies: Array<BaseCoordinatorProtocol> = []
    private var callback: ___VARIABLE_sceneName___CoordinatorCall?
    
    private let navigationController: UINavigationController
    
    private var controller: ___VARIABLE_sceneName___ControllerProtocol?
    private var interactor: ___VARIABLE_sceneName___InteractorProtocol
    private var presenter: ___VARIABLE_sceneName___PresenterProtocol
    
    required init(useCase: ___VARIABLE_sceneName___CoordinatorUseCaseProtocol) {
        navigationController = useCase.navigationController
        interactor = ___VARIABLE_sceneName___Interactor()
        presenter = ___VARIABLE_sceneName___Presenter()
        interactor.presenter = self.presenter
        
        controller = ___VARIABLE_sceneName___Controller(interactor: interactor, callback: processControllerCallback())
        presenter.controller = self.controller
    }
    
    func start(callback: @escaping ___VARIABLE_sceneName___CoordinatorCall) {
        self.callback = callback
        let view: ___VARIABLE_sceneName___ViewProtocol & UIViewController = ___VARIABLE_sceneName___View()
        controller?.view = view
        self.navigationController.pushViewController(view, animated: true)
    }
}

private extension ___VARIABLE_sceneName___Coordinator {
    
    func processControllerCallback() -> ___VARIABLE_sceneName___ControllerCallback {
        
        return {[weak self] type in
            switch type {
            case .close:
                print("Closed")
                self?.callback.map { $0(.close)}
            case .back:
                print("Back")
            }
        }
    }
    
}
