//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects
//

import Foundation

enum ___VARIABLE_sceneName___ViewCallbackType {
    case back
}

typealias ___VARIABLE_sceneName___ViewCallback = ((___VARIABLE_sceneName___ViewCallbackType) -> ())

protocol ___VARIABLE_sceneName___ViewModelProtocol {
        
}

protocol ___VARIABLE_sceneName___ViewProtocol: AnyObject {
    
    var callback: ___VARIABLE_sceneName___ViewCallback? { set get }
    func display(viewModel: ___VARIABLE_sceneName___ViewModelProtocol)
}
