//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects
//

import UIKit

class ___VARIABLE_sceneName___View: UIViewController, ___VARIABLE_sceneName___ViewProtocol {
     
    var callback: ___VARIABLE_sceneName___ViewCallback?
        
    override func viewDidLoad() {
        super.viewDidLoad()
        setupUI()
    }
    
    func display(viewModel: ___VARIABLE_sceneName___ViewModelProtocol) {
        
    }
}

private extension ___VARIABLE_sceneName___View {
    func setupUI() {
        
    }
}
