//
//  ExamplePresenter.swift
//  VIPCleanPOC
//
//  Created by Mohamed Hisham on 10/11/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects
//

import UIKit

class ExamplePresenter: ExamplePresenterProtocol {
    struct ViewModel: ExampleViewModelProtocol {
        var username: String
        var email: String
        var balance: String
    }
    
    var controller: ExampleControllerProtocol?
    
    func processSuccess(result: ServerResponseUserData) {
        let viewModel = mapServerModelToViewModel(serverModel: result)
        self.controller?.displayOnView(viewModel: viewModel)
    }
    
    func mapServerModelToViewModel(serverModel:ServerResponseUserData) -> ViewModel{
        ViewModel(username: serverModel.username,
                  email: serverModel.email,
                  balance: serverModel.balance)
    }
    
}
