//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects
//

import UIKit

class ___VARIABLE_sceneName___Presenter: ___VARIABLE_sceneName___PresenterProtocol {
    
    struct ViewModel: ___VARIABLE_sceneName___ViewModelProtocol {
        
    }
    
    var controller: ___VARIABLE_sceneName___ControllerProtocol?
    
    func processViewLoaded() {
        
        controller?.displayOnView(viewModel: ViewModel())
    }
}
